// core/kpiDefaults.js — default Tier 1 KPI library seeded for every new user.
// Single source of truth for the starter set; users edit their own copy (stored
// in MongoDB via models/KpiLibrary). Shape: { template, kpi, category, weight,
// direction } where direction is "Higher" | "Lower".
//
// Generated from files/KPI_Library.xlsx (Tier1 sheet). 70 rows.

const DEFAULT_TIER1_ROWS = [
  { template: "Lending Template", kpi: "ROA", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Lending Template", kpi: "ROE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Lending Template", kpi: "PAT Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Lending Template", kpi: "Book Value Growth", category: "Growth", weight: 15, direction: "Higher" },
  { template: "Lending Template", kpi: "Debt/Equity", category: "Capital", weight: 15, direction: "Lower" },
  { template: "Insurance Template", kpi: "ROE", category: "Profitability", weight: 30, direction: "Higher" },
  { template: "Insurance Template", kpi: "Revenue Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Insurance Template", kpi: "PAT Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Insurance Template", kpi: "Book Value Growth", category: "Growth", weight: 15, direction: "Higher" },
  { template: "Insurance Template", kpi: "Debt/Equity", category: "Capital", weight: 15, direction: "Lower" },
  { template: "Asset Management Template", kpi: "Revenue Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Asset Management Template", kpi: "EBITDA Margin", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Asset Management Template", kpi: "ROE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Asset Management Template", kpi: "PAT Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Asset Management Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Technology Template", kpi: "Revenue Growth", category: "Growth", weight: 25, direction: "Higher" },
  { template: "Technology Template", kpi: "EBITDA Margin", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Technology Template", kpi: "ROCE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Technology Template", kpi: "PAT Growth", category: "Growth", weight: 15, direction: "Higher" },
  { template: "Technology Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Consumer Brand Template", kpi: "Revenue Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Consumer Brand Template", kpi: "EBITDA Margin", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Consumer Brand Template", kpi: "ROCE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Consumer Brand Template", kpi: "FCF Conversion", category: "Efficiency", weight: 20, direction: "Higher" },
  { template: "Consumer Brand Template", kpi: "Working Capital Days", category: "Efficiency", weight: 15, direction: "Lower" },
  { template: "Retail Template", kpi: "Revenue Growth", category: "Growth", weight: 25, direction: "Higher" },
  { template: "Retail Template", kpi: "Asset Turnover", category: "Efficiency", weight: 20, direction: "Higher" },
  { template: "Retail Template", kpi: "ROCE", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Retail Template", kpi: "Working Capital Days", category: "Efficiency", weight: 20, direction: "Lower" },
  { template: "Retail Template", kpi: "EBITDA Margin", category: "Profitability", weight: 15, direction: "Higher" },
  { template: "Manufacturing Template", kpi: "Revenue Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Manufacturing Template", kpi: "EBITDA Margin", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Manufacturing Template", kpi: "ROCE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Manufacturing Template", kpi: "Asset Turnover", category: "Efficiency", weight: 20, direction: "Higher" },
  { template: "Manufacturing Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Specialty Manufacturing Template", kpi: "Revenue Growth", category: "Growth", weight: 25, direction: "Higher" },
  { template: "Specialty Manufacturing Template", kpi: "EBITDA Margin", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Specialty Manufacturing Template", kpi: "ROCE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Specialty Manufacturing Template", kpi: "PAT Growth", category: "Growth", weight: 15, direction: "Higher" },
  { template: "Specialty Manufacturing Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Commodity Template", kpi: "Revenue Growth", category: "Growth", weight: 15, direction: "Higher" },
  { template: "Commodity Template", kpi: "EBITDA Margin", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Commodity Template", kpi: "ROCE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Commodity Template", kpi: "Debt/Equity", category: "Capital", weight: 20, direction: "Lower" },
  { template: "Commodity Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Infrastructure Template", kpi: "Revenue Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Infrastructure Template", kpi: "EBITDA Margin", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Infrastructure Template", kpi: "ROCE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Infrastructure Template", kpi: "Asset Turnover", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Infrastructure Template", kpi: "Working Capital Days", category: "Efficiency", weight: 20, direction: "Lower" },
  { template: "Utility Template", kpi: "ROE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Utility Template", kpi: "ROCE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Utility Template", kpi: "Debt/Equity", category: "Capital", weight: 25, direction: "Lower" },
  { template: "Utility Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Utility Template", kpi: "Revenue Growth", category: "Growth", weight: 10, direction: "Higher" },
  { template: "Asset Utilization Template", kpi: "Revenue Growth", category: "Growth", weight: 25, direction: "Higher" },
  { template: "Asset Utilization Template", kpi: "EBITDA Margin", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Asset Utilization Template", kpi: "ROCE", category: "Profitability", weight: 20, direction: "Higher" },
  { template: "Asset Utilization Template", kpi: "Asset Turnover", category: "Efficiency", weight: 20, direction: "Higher" },
  { template: "Asset Utilization Template", kpi: "Debt/Equity", category: "Capital", weight: 15, direction: "Lower" },
  { template: "Real Estate Template", kpi: "ROE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Real Estate Template", kpi: "Book Value Growth", category: "Growth", weight: 25, direction: "Higher" },
  { template: "Real Estate Template", kpi: "PAT Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Real Estate Template", kpi: "Debt/Equity", category: "Capital", weight: 15, direction: "Lower" },
  { template: "Real Estate Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Capital Allocation Template", kpi: "ROE", category: "Profitability", weight: 25, direction: "Higher" },
  { template: "Capital Allocation Template", kpi: "Book Value Growth", category: "Growth", weight: 25, direction: "Higher" },
  { template: "Capital Allocation Template", kpi: "PAT Growth", category: "Growth", weight: 20, direction: "Higher" },
  { template: "Capital Allocation Template", kpi: "FCF Conversion", category: "Efficiency", weight: 15, direction: "Higher" },
  { template: "Capital Allocation Template", kpi: "Debt/Equity", category: "Capital", weight: 15, direction: "Lower" },
];

module.exports = { DEFAULT_TIER1_ROWS };
