// services/mailer.js — Gmail SMTP via nodemailer.
// Requires GMAIL_APP_PASSWORD in server .env (Google App Password, not the account password).
// To generate one: Google Account → Security → 2-Step Verification → App passwords.

const nodemailer = require("nodemailer");

const SENDER = "noreply@thinkvest.in";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: { user: SENDER, pass: process.env.GMAIL_APP_PASSWORD },
});

const BRAND_HEADER = `
  <div style="padding:24px 32px 16px;border-bottom:1px solid #f0f0f0">
    <span style="font-size:20px;font-weight:800;letter-spacing:-0.03em;color:#4F46E5">Think<span style="color:#0f0f0f">Vest</span></span>
  </div>
`;

const BRAND_FOOTER = `
  <div style="padding:16px 32px;border-top:1px solid #f0f0f0;margin-top:8px">
    <p style="margin:0;color:#aaa;font-size:11px">© ThinkVest · noreply@thinkvest.in</p>
  </div>
`;

async function sendOtpEmail(to, otp, purpose) {
  if (!process.env.GMAIL_APP_PASSWORD) {
    throw new Error("Email service is not configured (GMAIL_APP_PASSWORD not set)");
  }
  const subjects = {
    reset:  "Reset your ThinkVest password",
    change: "Verify your ThinkVest password change",
    verify: "Verify your ThinkVest email address",
  };
  const actions = {
    reset:  "reset your password",
    change: "change your password",
    verify: "verify your email address",
  };
  const subject = subjects[purpose] || "Your ThinkVest verification code";
  const action  = actions[purpose]  || "continue";

  await transporter.sendMail({
    from: `"ThinkVest" <${SENDER}>`,
    to,
    subject,
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:480px;margin:0 auto;color:#0f0f0f">
        <div style="background:linear-gradient(135deg,#4F46E5 0%,#6366F1 100%);height:4px;border-radius:4px 4px 0 0"></div>
        <div style="background:#fff;border:1px solid #e5e5e5;border-top:none;border-radius:0 0 12px 12px">
          ${BRAND_HEADER}
          <div style="padding:28px 32px 32px">
            <h2 style="margin:0 0 12px;font-size:20px;font-weight:700;letter-spacing:-0.02em">Your verification code</h2>
            <p style="margin:0 0 24px;color:#666;font-size:15px">Use this code to ${action}:</p>
            <div style="font-size:40px;font-weight:700;letter-spacing:10px;padding:20px;background:#f4f4f8;text-align:center;border-radius:10px;margin:0 0 24px;color:#4F46E5">${otp}</div>
            <p style="margin:0 0 8px;color:#666;font-size:13px">This code expires in <strong>10 minutes</strong>.</p>
            <p style="margin:0;color:#999;font-size:12px">If you didn&apos;t request this, you can safely ignore this email.</p>
          </div>
          ${BRAND_FOOTER}
        </div>
      </div>
    `,
  });
}

async function sendRankingsSummaryEmail(to, pdfBuffer, templateCount) {
  if (!process.env.GMAIL_APP_PASSWORD) {
    throw new Error("Email service is not configured (GMAIL_APP_PASSWORD not set)");
  }
  const templateWord = templateCount === 1 ? "template" : "templates";
  await transporter.sendMail({
    from: `"ThinkVest" <${SENDER}>`,
    to,
    subject: "Your ThinkVest rankings summary",
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:520px;margin:0 auto;color:#0f0f0f">
        <div style="background:linear-gradient(135deg,#4F46E5 0%,#6366F1 100%);height:4px;border-radius:4px 4px 0 0"></div>
        <div style="background:#fff;border:1px solid #e5e5e5;border-top:none;border-radius:0 0 12px 12px">
          ${BRAND_HEADER}
          <div style="padding:28px 32px 32px">
            <h2 style="margin:0 0 12px;font-size:20px;font-weight:700;letter-spacing:-0.02em">Rankings summary attached</h2>
            <p style="margin:0 0 20px;color:#666;font-size:15px">
              Top 10 companies across <strong>${templateCount} ${templateWord}</strong> are in the attached PDF report.
            </p>
            <p style="margin:0;color:#999;font-size:12px">Generated by the ThinkVest equity ranking platform.</p>
          </div>
          ${BRAND_FOOTER}
        </div>
      </div>
    `,
    attachments: [{
      filename: "thinkvest_rankings_summary.pdf",
      content: pdfBuffer,
      contentType: "application/pdf",
    }],
  });
}

async function sendResultsEmail(to, xlsxBuffer, filename) {
  if (!process.env.GMAIL_APP_PASSWORD) {
    throw new Error("Email service is not configured (GMAIL_APP_PASSWORD not set)");
  }
  await transporter.sendMail({
    from: `"ThinkVest" <${SENDER}>`,
    to,
    subject: "Your ThinkVest ranking results are ready",
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:480px;margin:0 auto;color:#0f0f0f">
        <div style="background:linear-gradient(135deg,#4F46E5 0%,#6366F1 100%);height:4px;border-radius:4px 4px 0 0"></div>
        <div style="background:#fff;border:1px solid #e5e5e5;border-top:none;border-radius:0 0 12px 12px">
          ${BRAND_HEADER}
          <div style="padding:28px 32px 32px">
            <h2 style="margin:0 0 12px;font-size:20px;font-weight:700;letter-spacing:-0.02em">Your ranking results are ready</h2>
            <p style="margin:0 0 24px;color:#666;font-size:15px">The ThinkVest pipeline has finished ranking your equity universe. Find the colour-coded multi-sheet Excel report attached.</p>
            <p style="margin:0;color:#999;font-size:12px">Sent from the ThinkVest equity ranking platform.</p>
          </div>
          ${BRAND_FOOTER}
        </div>
      </div>
    `,
    attachments: [{
      filename,
      content: xlsxBuffer,
      contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }],
  });
}

module.exports = { sendOtpEmail, sendResultsEmail, sendRankingsSummaryEmail };
